
# ░░░█▄█░▀▄▀▒█▀▄▒█▀▄░░░██▄▒▄▀▄░▄▀▀▒██▀
# ▒░▒█▒█░▒█▒░█▀▒░█▀▄▒░▒█▄█░█▀█▒▄██░█▄▄

dwindle {
    pseudotile = no
    preserve_split = yes
    no_gaps_when_only = 0
}

general {
    gaps_in = 2
    gaps_out = 8
    border_size = 3
    layout = dwindle
    resize_on_border = true
    allow_tearing = true
    col.active_border = rgb(d1e9fe)
    col.inactive_border = rgba(595959aa)
}

xwayland {
    force_zero_scaling = true
}

opengl {
   nvidia_anti_flicker = true
   force_introspection = 1
}

render {
    explicit_sync = 1
    explicit_sync_kms = 1
    direct_scanout = false
}

misc {
    vfr = false
    vrr = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    mouse_move_enables_dpms = true
    enable_swallow = true
    swallow_regex = ^(foot)$
    focus_on_activate = true
    initial_workspace_tracking = 0
    mouse_move_focuses_monitor = true
    disable_splash_rendering = true
    middle_click_paste = false
}
