
# ░░░█▄█░▀▄▀▒█▀▄▒█▀▄░░▒██▀░▀▄▀▒██▀░▄▀▀
# ▒░▒█▒█░▒█▒░█▀▒░█▀▄▒░░█▄▄░█▒█░█▄▄░▀▄▄

# Startup
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Polkit (Polkit Gnome / KDE)
exec-once = /home/knoodle/bin/polkit-init

# Startup Applications
exec-once = swww-daemon
exec-once = waybar &
exec-once = swaync &

# Clipboard Manager
exec-once = copyq --start-server

# XDG Desktop Portal
exec-once = /home/knoodle/bin/portal-hyprland
exec-once = gammastep -l 35.084385:-106.650421 -O 2500
exec-once = ~/bin/setup-interface.sh

exec = qpwgraph -a -m /pool/king/patchbay.qpwgraph

exec-once = nm-applet --no-agent --indicator
exec-once = 1password --silent
exec-once = Discord
exec-once = flatpak run com.discordapp.DiscordCanary & flatpak run com.slack.Slack
exec-once = steam -silent
exec-once = prismlauncher
exec-once = chatterino
exec-once = codium .config/the.code-workspace
exec-once = ps aux | grep '[n]xplayer.bin --session MBP.nxs' || /usr/NX/bin/nxplayer --session MBP.nxs
exec-once = firefox