# =====================================
# Hyprland [Graphics] Configuration
# =====================================

xwayland {
    force_zero_scaling = true
}

opengl {
   nvidia_anti_flicker = true
   force_introspection = 1
}

render {
    explicit_sync = 1
    explicit_sync_kms = 1
    direct_scanout = false
}