
# ░█▄█░▀▄▀▒█▀▄▒█▀▄░░░█░█▄░█▒█▀▄░█▒█░▀█▀
# ▒█▒█░▒█▒░█▀▒░█▀▄▒░░█░█▒▀█░█▀▒░▀▄█░▒█▒

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 1

    touchpad {
        disable_while_typing = true
        natural_scroll = yes
        tap-to-click = true
    }

    touchdevice {
        enabled = false
    }
    
    numlock_by_default = true
    left_handed = false
    follow_mouse = true
    float_switch_override_focus = false
}

binds {
    workspace_back_and_forth = true
    allow_workspace_cycles = true
    pass_mouse_when_bound = false
}

device {
    name = logitech-g-pro--1
    sensitivity = -0.25
    accel_profile = adaptive
}

cursor {
    no_hardware_cursors = true
    enable_hyprcursor = true
    warp_on_change_workspace = true
    no_warps = true
}

gestures {
    workspace_swipe = off
}