
# ░█▄█░▀▄▀▒█▀▄▒█▀▄░░░█▄▒▄█░▄▀▄░█▄░█░█░▀█▀░▄▀▄▒█▀▄
# ▒█▒█░▒█▒░█▀▒░█▀▄▒░░█▒▀▒█░▀▄▀░█▒▀█░█░▒█▒░▀▄▀░█▀▄

$cmon = DP-3      # Center
$umon = DP-2      # Upper
$rmon = DP-1      # Right
$lmon = HDMI-A-1  # Left

monitor = $cmon,2560x1440@143.91,0x0,1
monitor = $umon,1920x1080@143.85,0x-1080,1
monitor = $lmon,1920x1080@60,-1920x444,1
monitor = $rmon,1920x1080@60,2560x-888,1,transform,3

# Workspace Rules
workspace = 1, monitor:$lmon, persistent:true
workspace = 2, monitor:$rmon, persistent:true
workspace = 3, monitor:$umon, persistent:true
workspace = 7, monitor:$umon, persistent:true
workspace = 4, monitor:$cmon, persistent:true
workspace = 5, monitor:$cmon, persistent:true
workspace = 6, monitor:$cmon, persistent:true

# Applications
windowrulev2 = workspace 1, class:^(com.chatterino.chatterino)$
windowrulev2 = workspace 2, class:^(discord|com.discordapp.DiscordCanary)$
windowrulev2 = workspace 3, class:^(Nxplayer.bin)$
windowrulev2 = workspace 4, class:^(codium-url-handler)$
windowrulev2 = workspace 5, class:^(PrismLauncher|steam)$
windowrulev2 = workspace 6, class:^(org.mozilla.firefox|Cider)$
windowrulev2 = workspace 7, class:^(Slack)$
