# =====================================
# Hyprland [Rules] Configuration
# =====================================

# Waybar Transparency
layerrule = blur, waybar
layerrule = blurpopups, waybar
layerrule = ignorealpha 0.2, waybar

windowrulev2 = idleinhibit always, fullscreen:1
windowrulev2 = nodim, fullscreen:1

# Suppress maximize event for all windows
windowrulev2 = suppressevent maximize, class:.*

# Fullscreen borders
windowrulev2 = bordercolor rgb(FF0000),fullscreen:1

# Games
windowrulev2 = fullscreen, title:^(Juice Galaxy)$

# Waydroid
windowrulev2 = float, class:^(waydroid*)$
windowrulev2 = float, class:^(Waydroid*)$

# Chatterino
windowrulev2 = float, title:^(.*Usercard.*)$
windowrulev2 = stayfocused, title:^(.*Usercard.*)$
windowrulev2 = stayfocused, initialTitle:^(.*Usercard.*)$

# Steam
windowrulev2 = float, title:^(Friends List|Steam)$
windowrulev2 = float, class:^(steam)$

# NoMachine
windowrulev2 = fullscreen, class:^(Nxplayer.bin)$

# Size Windows
windowrulev2 = size 20% 30%, class:^(PrismLauncher)
windowrulev2 = size 20% 60%, title:(Friends List)$
windowrulev2 = size 40% 40%, title:(Library|1Password)$
windowrulev2 = size 35% 40%, title:^(Select Folder)$
windowrulev2 = size 35% 40%, class:^(kitty)$
windowrulev2 = size 45% 40%, class:^(thunar|Thunar|xarchiver)$
windowrulev2 = size 25% 60%, class:^(desmume)$
windowrulev2 = size 55% 65%, class:^(dev.zed.Zed|BCompare)$
windowrulev2 = size 50% 60%, class:^(org.rncbc.qpwgraph)$
windowrulev2 = size 60% 70%, class:^(kvantummanager|qt6ct|file-roller|org.gnome.FileRoller)$
windowrulev2 = size 40% 80%, class:^(org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$
windowrulev2 = size 70% 70%, class:^(xdg-desktop-portal-gtk)$

# Floating and Centered Windows
windowrulev2 = float, center, title:(1Password|thunar|Thunar|BCompare)$
windowrulev2 = float, center, class:^(kitty|lutris|itch|qt6cts|zenity|waypaper|desmume|imv|xarchiver|PrismLauncher)$
windowrulev2 = float, center, class:^(dev.zed.Zed|kvantummanager|xdg-desktop-portal-gtk|com.github.hluk.copyq)$
windowrulev2 = float, center, class:^(org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$
windowrulev2 = float, center, class:^(org.rncbc.qpwgraph|org.kde.gwenview|page.kramo.Cartridge|org.prismlauncher.PrismLauncher)$
windowrulev2 = float, center, class:^(file-roller|org.gnome.FileRoller|org.kde.ark|org.kde.dolphin)$

# Dimming / Opacity Windows (combined similar rules)
windowrulev2 = opacity 1 override, nodim override, class:^(mpv)$
windowrulev2 = opacity 1 override, nodim override, title:^(.*Alternate Player for Twitch.tv.*)
windowrulev2 = opacity 1 override, title:^(Picture-in-Picture)$
windowrulev2 = opacity 1 override, nodim override, initialTitle:^(Discord Popout)$
